language: ruby
rvm: 2.2
before_script:
  - gem install awesome_bot
  - npm install --global awesome-lint
script:
  - awesome_bot --allow-redirect --allow-dupe README.md
  - awesome-lint
notifications:
  email: true
